# Generated by Django 4.1.2 on 2022-11-03 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_cad_itens_auditaveis_fr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cad_mapeamento',
            options={'verbose_name': 'Cad_Mapeamento'},
        ),
    ]
