# Generated by Django 4.1.2 on 2022-11-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cad_mapeamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cad_mapeamento',
            options={'verbose_name': 'Mapeamento de Dados'},
        ),
    ]
