# Generated by Django 4.1.2 on 2022-11-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_cad_mapeamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cad_dados_previos',
            options={'verbose_name': 'Dados Prévio'},
        ),
        migrations.AlterModelOptions(
            name='cad_dpo',
            options={'verbose_name': 'Cadastro de DPO'},
        ),
        migrations.AlterModelOptions(
            name='cad_empresa',
            options={'verbose_name': 'Cadastro de Empresa'},
        ),
        migrations.AlterModelOptions(
            name='cad_equipes',
            options={'verbose_name': 'Cadastro de Equipe'},
        ),
        migrations.AlterModelOptions(
            name='cad_fornecedores',
            options={'verbose_name': 'Cadastro de Fornecedor'},
        ),
        migrations.AlterModelOptions(
            name='cad_itens_auditaveis',
            options={'verbose_name': 'Cadastro de Itens Auditaveis'},
        ),
        migrations.AlterModelOptions(
            name='cad_setores',
            options={'verbose_name': 'Cadastro de Setor'},
        ),
    ]
