# Generated by Django 4.1.2 on 2022-11-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cad_dados_previos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cad_fornecedores',
            options={'verbose_name': 'Cadastro de Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='cad_setores',
            options={'verbose_name': 'Cadastro de Setores'},
        ),
        migrations.AlterField(
            model_name='cad_dados_previos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cad_dpo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cad_empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cad_equipes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cad_fator_de_risco',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cad_fornecedores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cad_itens_auditaveis',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cad_setores',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
