# Generated by Django 4.1.2 on 2022-11-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_cad_dados_previos_resposta_alter_cad_dpo_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='dado',
            field=models.CharField(max_length=30),
        ),
    ]
