# Generated by Django 4.1.2 on 2022-11-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_cad_mapeamento_dado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='base_legal',
            field=models.CharField(blank=True, choices=[('Consentimento do titular', 'Consentimento do titular'), ('Legítimo interesse', 'Legítimo interesse'), ('Cumprimento de obrigação legal ou regulatória', 'Cumprimento de obrigação legal ou regulatória'), ('Tratamento pela administração pública', 'Tratamento pela administração pública'), ('Realização de estudos e de pesquisa', 'Realização de estudos e de pesquisa'), ('Execução ou preparação contratual', 'Execução ou preparação contratual'), ('Exercício regular de direitos', 'Exercício regular de direitos'), ('Proteção da vida e da incolumidade física', 'Proteção da vida e da incolumidade física'), ('Tutela de saúde do titular', 'Tutela de saúde do titular'), ('Proteção de crédito', 'Proteção de crédito')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='compartilhamento',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='impacto_pessoal',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='menor',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='missao_critica',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='necessario_consentimento',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='possui_consentimento',
            field=models.CharField(blank=True, choices=[('S', 'SIM'), ('N', 'NÃO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Dado Pessoal', 'Dado Pessoal'), ('Dado Sensível', 'Dado Sensível'), ('Dado Público', 'Dado Público'), ('Dado Anonimizado', 'Dado Anonimizado')], max_length=30, null=True),
        ),
    ]
