# Generated by Django 4.1.2 on 2022-11-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_cad_mapeamento_base_legal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_empresa',
            name='cep_empresa',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='cad_empresa',
            name='cidade_empresa',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cad_empresa',
            name='cnpj_empresa',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='cad_empresa',
            name='endereco_empresa',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='cad_empresa',
            name='estado_empresa',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cad_empresa',
            name='telefone_empresa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cad_itens_auditaveis',
            name='e',
            field=models.IntegerField(choices=[(1, 'SIM'), (0, 'NÃO')]),
        ),
        migrations.AlterField(
            model_name='cad_itens_auditaveis',
            name='icn',
            field=models.IntegerField(choices=[(1, 'BAIXO'), (2, 'NORMAL'), (3, 'MEDIO'), (4, 'ALTO'), (5, 'MUITO ALTO')]),
        ),
        migrations.AlterField(
            model_name='cad_itens_auditaveis',
            name='il',
            field=models.IntegerField(choices=[(1, 'BAIXO'), (2, 'NORMAL'), (3, 'MEDIO'), (4, 'ALTO'), (5, 'MUITO ALTO')]),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='impacto_pessoal',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cad_mapeamento',
            name='missao_critica',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=30, null=True),
        ),
    ]
